### ISSUE TITLE
Tool does not work if using the packages property inside workspaces

### ISSUE THREAD

**Issue by N0NamedGuy** [plantain-00/package-dependency-graph#11]
#### Version(if relevant): 1.14.3

When the workspace package.json defines its workspaces with the following format:

```json
{
    "workspaces": {
        "packages": ["./packages/*/js"]
    }
}
```
the tool will throw the following into the console:
```
rootPackageJson.workspaces.map is not a function
```

However by changing the workspace package.json to:
```json
{
    "workspaces": [
        "./packages/*/js"
    ]
}
```

it will work.

The workspaces.packages declaration is also an accepted form of declaring workspaces as per https://github.com/npm/rfcs/blob/main/implemented/0026-workspaces.md

**Comment by plantain-00** [comment]
released in v1.14.4
