### ISSUE TITLE
how to generate dep graph only for monorepo packages?

### ISSUE THREAD

**Issue by sibelius** [plantain-00/package-dependency-graph#13]
<img width="362" alt="image" src="https://github.com/plantain-00/package-dependency-graph/assets/2005841/a95d9c96-e533-45fd-bf20-bb7ae6f80061">

can I also generate just 1 single line per package?

**Comment by plantain-00** [comment]
Not sure what you need, maybe `--exclude-node_modules`

**Comment by sibelius** [comment]
I just wanna a better visualization, too much noise
