### ISSUE TITLE
Add graphviz-cli JS library to remove external graphviz dependency

### ISSUE THREAD

**Issue by mohanraj-r** [plantain-00/package-dependency-graph#3]
Thanks for developing this library 👍  I find it better for my needs than the half a dozen similar libs I tried out.

It would be great if you can integrate [prantlf/graphviz-cli](https://github.com/prantlf/graphviz-cli) with this library so that we can avoid depending on external graphviz installation. I am using the `prantlf/graphviz-cli` to process the dot file produced by `package-dependency-graph` and the output svg is exactly the same as produced by the external graphviz tool (`dot -Tsvg ...`). 

If you could integrate the [prantlf/graphviz-cli](https://github.com/prantlf/graphviz-cli) library with yours it would be great!

**Comment by plantain-00** [comment]
v1.8.0 should support it now.

**Comment by mohanraj-r** [comment]
Thanks @plantain-00 for the quick response.

I tried upgrading to v1.8.0 and noticed a issue. After upgrading `package-dependency-graph` no longer appears in `node_modules/.bin/` 
```
$ yarn package-dependency-graph
yarn run v1.22.4
error Command "package-dependency-graph" not found.
```

But once I downgraded back to v1.7.1 it works again.

One more comment: Is there a reason for pinning the version of graphviz-cli at 1 `"graphviz-cli": "1",` ?
E.g. why not allow sem ver as `"graphviz-cli": "^1.0.0",` ?

**Comment by plantain-00** [comment]
v1.8.1 should fix this.
`"graphviz-cli": "1"` is same as: `1 := 1.x.x := >=1.0.0 <2.0.0-0`

**Comment by mohanraj-r** [comment]
Thanks for the fix @plantain-00 

But as per [npm-semver](https://docs.npmjs.com/misc/semver) think `"^1.0.0"` with the `^` is what would translate to `1.x.x := >=1.0.0 <2.0.0-0`. Without the `^` wouldn't you be pinning the dependency at the exact version?

I also noticed the following in my `yarn.lock` after updating to `v1.8.0`
```
graphviz-cli@1, graphviz-cli@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/graphviz-cli/-/graphviz-cli-1.0.0.tgz#9a487ddce36b8f31a2cb27ad944f2126cb1b5d5d"
  integrity sha512-aPv1r4kP7I5cVGu73WjVc/h5OdebB0z+acWiN+0YFnSRK2UQlWudp/xlqXCQdn/b5caw0GSxLysZS60K5pqRJw==
  dependencies:
    "@aduh95/viz.js" "3.0.1"
```

You can see yarn has resolved the `graphviz-cli@^1.0.0` from my package.json and `graphviz-cli@1` dependency from your package separately. Also `^1.0.0` would be the default format used by yarn/npm when you add the dependency.

**Comment by plantain-00** [comment]
It's same for `1`, `1.x`, `^1.0.0`, they are all `>=1.0.0 <2.0.0`, I use `1` because it has less characters.

<img width="688" alt="屏幕快照 2020-08-06 09 55 08" src="https://user-images.githubusercontent.com/7639395/89481761-03c81a80-d7cb-11ea-8c83-be082b6be68a.png">

**Comment by mohanraj-r** [comment]
Interesting, thanks for the clarification. Anyways it caught my eye as it looked different/odd from the versions added by default by package managers.

Btw @plantain-00 can you please release v1.8.1 to npm so I can test it out.

**Comment by plantain-00** [comment]
v1.8.2 is available now.

**Comment by mohanraj-r** [comment]
Thanks @plantain-00 
Verified with new version - it works as expected.
