### ISSUE TITLE
Include devDependencies

### ISSUE THREAD

**Issue by ertrzyiks** [plantain-00/package-dependency-graph#7]
#### Code(if relevant):

```
const dependencies = await collectDependencies('.', true, ['packages'])
```

#### Expected:

`dependencies` includes also information about monorepo packages referenced in `devDependencies` field of package.json

#### Actual:
only `dependencies` are considered

**Comment by plantain-00** [comment]
v1.12.0 `collectDependencies` has 4th argument `includeDevDependencies`

**Comment by ertrzyiks** [comment]
I just forked the repo and tried to come up with PR and realized it's already fixed in my local clone 😱 
 Thank you very much @plantain-00 !

**Comment by ertrzyiks** [comment]
Just test, works like a charm 🏅
