### ISSUE TITLE
[bug] Error when running `--graphviz` option

### ISSUE THREAD

**Issue by Jym77** [plantain-00/package-dependency-graph#8]
#### Environment(if relevant):

WSL running
Linux  4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 GNU/Linux

#### Code(if relevant):

Trying to build the dependency graph for [this repo](https://github.com/Siteimprove/alfa) fails with the `--graphviz` option but succeeds without it

```shell
alfa (main=)$ package-dependency-graph --graphviz --png foo.png
Error: syntax error in line 35 near '.'

alfa (main=)$ package-dependency-graph --png foo.png
package-dependency-graph success.
```

#### Expected:

Dependency graph is built, or an helpful error message is displayed

#### Actual:

I have no real idea why this fail, whether this is due to a bug in `package-dependency-graph` or some weird setting on my side, I don't even know which file has the syntax error.

**Comment by plantain-00** [comment]
I don't have Windows, I tried to run it on a MacBook, it doesn't show any error.
The error seems produced by `graphviz-cli`.
You can add `--dot a.dot` to see the errored dot file.

**Comment by Jym77** [comment]
Thanks.
Seems to be a problem with a dot in a package name (`zone.js`), line 35 is:
> `_siteimprove_alfa_angular -> zone.js[color = "#00ffff"]`

Not sure why only the graphviz export is affected…

(and for my use case, I only need my own packages, so `--exclude-node_modules=true` does remove it and solves my problem 😄 )

**Comment by Jym77** [comment]
I confirm I no longer encounter the issue 👍
