### ISSUE TITLE
[question] grouping packages in huge monorepo

### ISSUE THREAD

**Issue by Jym77** [plantain-00/package-dependency-graph#9]
So, I'm running `package-dependency-graph` on [this repo](https://github.com/Siteimprove/alfa) with almost 100 packages…
The result is definitely interesting but not very readable or helpful 😅 Which is expected, I still love the tool 😄 
![Dependency graph of Alfa](https://user-images.githubusercontent.com/19969498/156786756-e7555505-e68d-4ec8-8f85-dda942a92cc0.png)

Now, the thing is that I do know stuff about my repo that I'd like to tell `package-dependency-graph` in order to help it build a clearer view…
Typically, I know that a bunch of packages are test framework or browser automation integrations (`alfa-chai`, `alfa-jest`, `alfa-playwright`, `alfa-puppeteer`, …) These most likely have very similar dependencies inside my project, and do belong to a natural "group".
Ideally, I'd like to be able to create a "meta package" `test-integration` that could be drawn a single box (maybe with smaller boxes inside) and have a single set of arrows going out (to all the deps from the content of the box).

Would you see a not too difficult way to achieve that? For now I don't mind monkey-patching intermediate data of the various components, but I'm not sure where to start 🤔 
(e.g., grab the result of `package-dependency-collect` and do some manual or programmatic transformation on it to pretend that packages A and B are actually both part of package Foo, and then run the next step to build the graph)
(is there an easy way to run the various steps one by one so I can get a look at the exchanged data and figure out if/how I can hack it?)

**Comment by plantain-00** [comment]
Here is the API: https://github.com/plantain-00/package-dependency-graph/tree/master/packages/core

**Comment by plantain-00** [comment]
`v1.13.0` supports groups now.

**Comment by Jym77** [comment]
Looks great! Thanks for the fast patch 🙏

**Comment by Jym77** [comment]
Much better now 🎉 
![Dependency graph of Alfa](https://user-images.githubusercontent.com/19969498/157044174-afc1b354-e223-44f0-8922-e8e06e5b9a33.png)

What would it take to allow nested levels of grouping? My limited knowledge of `.dot` files says it should be possible, but I'm not sure how hard it would be…

The API I'm thinking about would be extending the current groups one with an array of strings (listing all the group hierarchy):
```
"group": ["sub group 1", "group A", "super group"]
```
to indicate that the package is in "sub group 1" which is itself part of "group A", again nested into "super group".

However, such an API does create redundancy if another package is in 
```
"group": ["sub group 2", "group A", "super group"]
```
then we've told twice that "group A" is part of "super group" which is both not very DRY and prone to error that would need to be handled (probably just crashing if seeing `["group A", "another super group"]` somewhere else 🤔 )

Would you think this is doable 🙏 ?

**Comment by plantain-00** [comment]
v1.14.1 supports nested groups now.

**Comment by Jym77** [comment]
Yes, but my project being TS already, I'd rather work with TS 😄 (and anyway, `ts-node` is now a regular dependency unless you decide to forbid TS config files).

**Comment by Jym77** [comment]
It seems that there is an error if a group contains only subgroups but no individual items).
This generates an empty line in the `.dot` but keeps the trailing semi-colon which errors it.

with:
```json
{
          name: "Computations",
          children: [
            {
              name: "Asynchronous",
              children: [
                "@siteimprove/alfa-future",
                "@siteimprove/alfa-promise",
                "@siteimprove/alfa-thenable",
              ],
            },
            {
              name: "Synchronous",
              children: [
                "@siteimprove/alfa-lazy",
                "@siteimprove/alfa-trampoline",
              ],
            },
          ],
        },
```
I got the errounous
```
subgraph cluster_Computations {
      ;                                                               <= lone ';' breaks .dot syntax
      subgraph cluster_Asynchronous {
        _siteimprove_alfa_future _siteimprove_alfa_promise _siteimprove_alfa_thenable;

        label = "Asynchronous";
        color = "#7f7f7f";
      }
    
      subgraph cluster_Synchronous {
        _siteimprove_alfa_lazy _siteimprove_alfa_trampoline;

        label = "Synchronous";
        color = "#7f7fff";
      }
    
      label = "Computations";
      color = "#7f7f00";
    }
```

**Comment by plantain-00** [comment]
v1.14.3 should fix this.

**Comment by Jym77** [comment]
Things work fine for me now 🎉 
Thanks a lot for your responsiveness and quick updates to the packages.
Closing this.
